---
- hosts: localhost
  tasks:
    - name: Adding MSSQL Repository Key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    - name: Add MSSQL Repository
      apt_repository: 
        repo: deb https://packages.microsoft.com/ubuntu/16.04/mssql-server xenial main
        state: present
    - name: Installs MSSQL
      apt: pkg=mssql-server state=installed update_cache=true
